my_printf
simple-lemon/arc-01-my_printf pull request #1
Opened 2023-12-06 10:22 UTC by GlitchLxrd

2023-12-06 17:42 UTC, GlitchLxrd commented
[README (1).md](https://github.com/simple-lemon/arc-01-my_printf/files/13589474/README.1.md)
I forgot to add README to the pull request

2023-12-07 05:26 UTC, simple-lemon requested changes
Please make sure to include the README file in your code repository and ensure it is up to date and well-written.

2023-12-07 11:18 UTC, GlitchLxrd commented
I've just commited the makefile , please check it

2023-12-11 05:55 UTC, simple-lemon requested changes
The task includes format specifiers %o, %u, and %x, but these are not implemented in your my_printf logic. This will lead to undefined behavior if these specifiers are used. You should implement these functionalities.

In my_putnbr, you're recursively calling the function even for single-digit numbers. This is not the most efficient approach, especially for larger numbers. An iterative solution might be more efficient.
For each digit in the number, a new call to my_putnbr is made. For example, if the number is 12345, my_putnbr is called five times - once for each digit. Recursive calls add overhead due to function invocation and can also lead to a stack overflow for very large inputs.

Your code lacks comments. Adding comments explaining the functionality of each function and the purpose of major code blocks would make your code more readable and maintainable.

2023-12-11 06:02 UTC, simple-lemon commented
In summary, your implementation of a basic printf-like function is a great learning exercise. It demonstrates your understanding of variadic functions, string manipulation, and basic I/O in C. By addressing the above points, you can improve the robustness, functionality, and efficiency of your code.

2026-07-31 07:10 UTC, closed without merging